#!/bin/bash
#PBS -N parse_bcac_erpos
#PBS -S /bin/bash
#PBS -l walltime=1:00:00
#PBS -l mem=32gb
#PBS -l nodes=1:ppn=1

#PBS -o logs/parse_bcac_erpos.log

### Standard Error and Output to same file
#PBS -j oe

# Sample size source for ER+ BRCA:
# https://bcac.ccge.medschl.cam.ac.uk/files/gwas-icogs-onco-summary-numbers_michailidou_Nat_2017.xlsx

module load gcc/6.2.0
module load python/3.5.3

cd $PBS_O_WORKDIR

python3 /gpfs/data/gao-lab/Julian/software/summary-gwas-imputation/src/gwas_parsing.py \
-gwas_file ../input/oncoarray_bcac_public_release_oct17.txt.gz \
-output_column_map var_name variant_id \
-output_column_map a0 non_effect_allele \
-output_column_map a1 effect_allele \
-output_column_map bcac_onco_icogs_gwas_erpos_beta effect_size \
-output_column_map bcac_onco_icogs_gwas_erpos_se standard_error \
-output_column_map bcac_onco_icogs_gwas_erpos_eaf_controls frequency \
-output_column_map bcac_onco_icogs_gwas_erpos_P1df pvalue \
-output_column_map position_b37 position \
-output_column_map chr chromosome \
--chromosome_format \
--insert_value sample_size 175475 --insert_value n_cases 69501 \
-output_order variant_id panel_variant_id chromosome position effect_allele non_effect_allele frequency pvalue zscore effect_size standard_error sample_size n_cases \
-liftover ../input/hg19ToHg38.over.chain.gz \
-snp_reference_metadata ../input/gtex_v8_eur_filtered_maf0.01_monoallelic_variants.txt.gz METADATA \
-output ../output/metaxcan_gwas_parse/BCAC_ERPOS_BreastCancer_EUR.txt.gz

# --keep_all_original_entries \
