#!/bin/bash
#PBS -N erpos_post_proc
#PBS -S /bin/bash
#PBS -l walltime=04:00:00
#PBS -l mem=16gb
#PBS -l nodes=1:ppn=1
#PBS -o logs/${PBS_JOBNAME}.log
### Standard Error and Output to same file
#PBS -j oe

#######################################################################################################################
#CRI submission dandruff

module load gcc/6.2.0
module load python/3.5.3

cd $PBS_O_WORKDIR

python3 /gpfs/data/gao-lab/Julian/software/summary-gwas-imputation/src/gwas_summary_imputation_postprocess.py \
-gwas_file ../output/metaxcan_gwas_parse/BCAC_ERPOS_BreastCancer_EUR.txt.gz \
-folder ../output/metaxcan_gwas_impute_regions/ \
-pattern BCAC_ERPOS_BreastCancer_EUR* \
-parsimony 9 \
-output ../output/metaxcan_gwas_imputed/BCAC_ERPOS_BreastCancer_EUR.txt.gz
